In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

In [2]:
from google.colab import files
uploaded = files.upload()

Saving hacker_news_posts.zip to hacker_news_posts.zip

In [3]:
# Load the dataset
df = pd.read_csv("hacker_news_posts.zip")

# Display the first few rows
df.head()

,id,title,url,num_points,num_comments,author,created_at
0,12579008,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,altstar,9/26/2016 3:26
1,12579005,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,blacksqr,9/26/2016 3:24
2,12578997,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,pavel_lishin,9/26/2016 3:19
3,12578989,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,poindontcare,9/26/2016 3:16
4,12578979,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,markgainor1,9/26/2016 3:14

In [4]:
# Check the dataset columns and data types
df.info()
# Summarize the basic statistics of the dataset
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293119 entries, 0 to 293118
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            293119 non-null  int64
 1   title         293119 non-null  object
 2   url           279256 non-null  object
 3   num_points    293119 non-null  int64
 4   num_comments  293119 non-null  int64
 5   author        293119 non-null  object
 6   created_at    293119 non-null  object
dtypes: int64(3), object(4)
memory usage: 15.7+ MB

                 id     num_points   num_comments
count  2.931190e+05  293119.000000  293119.000000
mean   1.133046e+07      15.025324       6.525544
std    6.961055e+05      58.504103      30.376319
min    1.017690e+07       1.000000       0.000000
25%    1.071636e+07       1.000000       0.000000
50%    1.130303e+07       2.000000       0.000000
75%    1.193152e+07       4.000000       1.000000
max    1.257901e+07    5771.000000    2531.000000

In [5]:
df.isnull().sum()

id                  0
title               0
url             13863
num_points          0
num_comments        0
author              0
created_at          0
dtype: int64

In [6]:

del df['url']

print(df)

              id                                              title  \
0       12579008  You have two days to comment if you want stem ...
1       12579005                         SQLAR  the SQLite Archiver
2       12578997  What if we just printed a flatscreen televisio...
3       12578989                                  algorithmic music
4       12578979  How the Data Vault Enables the Next-Gen Data W...
...          ...                                                ...
293114  10176919        Ask HN: What is/are your favorite quote(s)?
293115  10176917  Attention and awareness in stage magic: turnin...
293116  10176908                  Dying vets fuck you letter (2013)
293117  10176907  PHP 7 Coolest Features: Space Ships, Type Hint...
293118  10176903  Toyota Establishes Research Centers with MIT a...

        num_points  num_comments        author      created_at
0                1             0       altstar  9/26/2016 3:26
1                1             0      blacksqr  9/26/2016 3:24
2                1             0  pavel_lishin  9/26/2016 3:19
3                1             0  poindontcare  9/26/2016 3:16
4                1             0   markgainor1  9/26/2016 3:14
...            ...           ...           ...             ...
293114          15            20      kumarski   9/6/2015 6:02
293115          14             0       stakent   9/6/2015 6:01
293116          10             2  mycodebreaks   9/6/2015 5:56
293117           2             0       Garbage   9/6/2015 5:55
293118           4             0        tim_sw   9/6/2015 5:50

[293119 rows x 6 columns]

In [7]:
df['created_at'] = pd.to_datetime(df['created_at'])
df['created_at'].head()

0   2016-09-26 03:26:00
1   2016-09-26 03:24:00
2   2016-09-26 03:19:00
3   2016-09-26 03:16:00
4   2016-09-26 03:14:00
Name: created_at, dtype: datetime64[ns]

In [8]:
# Now you can extract year, month, day, and hour
df["year"] = df["created_at"].dt.year
df["month"] = df["created_at"].dt.month
df["day"] = df["created_at"].dt.day
df["hour"] = df["created_at"].dt.hour

In [9]:
df.isnull().sum()

id              0
title           0
num_points      0
num_comments    0
author          0
created_at      0
year            0
month           0
day             0
hour            0
dtype: int64

In [10]:
df.head()

,id,title,num_points,num_comments,author,created_at,year,month,day,hour
0,12579008,You have two days to comment if you want stem ...,1,0,altstar,2016-09-26 03:26:00,2016,9,26,3
1,12579005,SQLAR the SQLite Archiver,1,0,blacksqr,2016-09-26 03:24:00,2016,9,26,3
2,12578997,What if we just printed a flatscreen televisio...,1,0,pavel_lishin,2016-09-26 03:19:00,2016,9,26,3
3,12578989,algorithmic music,1,0,poindontcare,2016-09-26 03:16:00,2016,9,26,3
4,12578979,How the Data Vault Enables the Next-Gen Data W...,1,0,markgainor1,2016-09-26 03:14:00,2016,9,26,3

In [11]:
# Separate the 'Ask HN' posts
ask_df = df[df['title'].str.startswith('Ask HN')]        #This line filters the data to find all posts where the title starts with the text 'Ask HN'.
                                                         #df['title'] refers to the column in the dataset that contains the titles of the posts.
                                                          #str.startswith('Ask HN') is a method that checks if the title of the post begins with the string ask_df.

# Separate the 'Show HN' posts
show_df = df[df['title'].str.startswith('Show HN')]         #Similarly, this line filters the dataset to find all posts where the title starts with 'Show HN'.

# Display the first few rows of each
ask_df.head(), show_df.head()

(           id                                              title  num_points  \
 10   12578908  Ask HN: What TLD do you use for local developm...           4
 42   12578522  Ask HN: How do you pass on your work when you ...           6
 76   12577908  Ask HN: How a DNS problem can be limited to a ...           1
 80   12577870  Ask HN: Why join a fund when you can be an angel?           1
 102  12577647  Ask HN: Someone uses stock trading as passive ...           5

      num_comments         author          created_at  year  month  day  hour
 10              7        Sevrene 2016-09-26 02:53:00  2016      9   26     2
 42              3     PascLeRasc 2016-09-26 01:17:00  2016      9   26     1
 76              0           kuon 2016-09-25 22:57:00  2016      9   25    22
 80              3  anthony_james 2016-09-25 22:48:00  2016      9   25    22
 102             2        00taffe 2016-09-25 21:50:00  2016      9   25    21  ,
            id                                              title  num_points  \
 52   12578335              Show HN: Finding puns computationally           2
 58   12578182  Show HN: A simple library for complicated anim...           1
 64   12578098      Show HN: WebGL visualization of DNA sequences           1
 70   12577991  Show HN: Pomodoro-centric, heirarchical projec...           2
 140  12577142  Show HN: Jumble  Essays on the go #PaulInYourP...           1

      num_comments        author          created_at  year  month  day  hour
 52              0         saamm 2016-09-26 00:36:00  2016      9   26     0
 58              0  christinecha 2016-09-26 00:01:00  2016      9   26     0
 64              0      grondilu 2016-09-25 23:44:00  2016      9   25    23
 70              0       dbranes 2016-09-25 23:17:00  2016      9   25    23
 140             1        ryderj 2016-09-25 20:06:00  2016      9   25    20  )

In [12]:
len(ask_df), len(show_df)

(9122, 10150)